In [21]:
import pandas as pd
import numpy as np
import tensorflow as tf
print(tf.__version__)


2.10.0


In [2]:
SEED = 1234

# Set seed for reproducibility
np.random.seed(seed=SEED)
tf.random.set_seed(SEED)
print(np,tf)

<module 'numpy' from 'c:\\Users\\jamez\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'> <module 'tensorflow' from 'c:\\Users\\jamez\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\__init__.py'>


In [3]:
# Constants
x = tf.constant(1)
print (x)


tf.Tensor(1, shape=(), dtype=int32)


In [4]:
#สามารถเป็นค่าคงที่เเบบ Arrys
x = tf.constant([ [1, 2, 3] , [4, 5, 6] ])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
# ตัวอย่างสร้าง tensor ขนาด 2 x 3 ซึ่งสมาชิกข้างในมัน random ด้วยรูปแบบ uniform distribution
x = tf.random.uniform((2, 3))
print(f'Type:{x.dtype}')
print(f'Size:{x.shape}')
print(f'Values:\n{x}')

Type:<dtype: 'float32'>
Size:(2, 3)
Values:
[[0.5380393  0.36461866 0.5816301 ]
 [0.24382842 0.43033564 0.90619123]]


In [8]:
print(x.numpy())

[[0.5380393  0.36461866 0.5816301 ]
 [0.24382842 0.43033564 0.90619123]]


In [9]:
x = tf.zeros((2,3))
print(x)
x = tf.ones((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


แปลงชนิดข้อมูลจาก List เป็น Tensor

In [11]:
# List → Tensor
x = tf.convert_to_tensor([[1, 2, 3], [4, 5, 6]],dtype="int32")
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [20]:
# NumPy array -> Tensor
x = tf.convert_to_tensor(np.random.rand(2,3),dtype = "int32")
print(x)  

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [26]:
# แปลงชนิดข้อมูลจาก DataFrame เป็น Tensor
df = pd.read_csv('../data/california_housing_train.csv')
print("Size of datafame:",df.shape)
x = tf.convert_to_tensor(df.values)
print(x)

Size of datafame: (17000, 9)
tf.Tensor(
[[-1.1431e+02  3.4190e+01  1.5000e+01 ...  4.7200e+02  1.4936e+00
   6.6900e+04]
 [-1.1447e+02  3.4400e+01  1.9000e+01 ...  4.6300e+02  1.8200e+00
   8.0100e+04]
 [-1.1456e+02  3.3690e+01  1.7000e+01 ...  1.1700e+02  1.6509e+00
   8.5700e+04]
 ...
 [-1.2430e+02  4.1840e+01  1.7000e+01 ...  4.5600e+02  3.0313e+00
   1.0360e+05]
 [-1.2430e+02  4.1800e+01  1.9000e+01 ...  4.7800e+02  1.9797e+00
   8.5800e+04]
 [-1.2435e+02  4.0540e+01  5.2000e+01 ...  2.7000e+02  3.0147e+00
   9.4600e+04]], shape=(17000, 9), dtype=float64)


เปลี่บนชนิดข้อมูลใน tersor

In [28]:
x =tf.random.uniform((2,3))
print(f'Type:{x.dtype}')
x = tf.convert_to_tensor(x.numpy(),dtype="float64")
print(f'Type:{x.dtype}')

Type:<dtype: 'float32'>
Type:<dtype: 'float64'>
